Доработка задания по основам и компонент MeetupDescription
js-tasks-ru/vue-20210511_nadezhdabilay pull request #5
Opened 2021-05-21 20:48 UTC by la-rivolta

2021-05-21 20:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-21 21:02 UTC, ShGKme requested changes
В нескольких задачах закоммиченный гит конфликт.

В 03-MeetupTitle требуются исправления по комментариям.
В 04-MeetupPageDraft требуется избавиться от вызова методов в шаблоне.

2021-05-21 21:02 UTC, ShGKme commented on 02-components/02-MeetupDescription/MeetupDescription.js
> +      default: null
Значение по умолчанию для строки лучше сделать пустой строкой или вообще не указывать. В компоненте ничего не сломается без этого.

2021-05-21 21:02 UTC, ShGKme commented on 02-components/02-MeetupDescription/index.html
> +    }
Начальный вариант должен был работать :)

2021-05-21 21:19 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-21 21:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-23 15:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-05-23 15:59 UTC, la-rivolta commented on 01-basics/04-MeetupPageDraft/index.html
> +                  <img class="icon" alt="icon" :src="setAgendaIcon(agendaItem)" />
Добрый день, Григорий!
Программу поправила, но не уверена, что все ок.

2021-05-23 19:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-23 20:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-23 20:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-23 20:20 UTC, ShGKme requested changes
В 04-MeetupPageDraft требуется переработать решение в соответствии с комментариями.
В 03-MeetupCover требуется небольшое исправление.
04-MeetupInfo не работает...

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/index.html
>      </div>
Изображение на фоне определяется CSS переменной `--bg-url` так же, как мы делали на вебинаре. Ссылка - часть стилей фона, а не целиком весь фон.

При этом, если у митапа нет изображения (`imageId === null`), то здесь получится некорректный стиль, который собьёт стиль с картинкой по умолчанию.

В следующей такой задачей это не пройдёт автоматическое тестирование.

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +    },
`imageId` может быть `null`. В этом случае ссылка здесь получается некорректная.

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +  methods:{
Пустой объект - не частный случай объекта с описанием митапа.

Хотя установка начального значения в `{}` избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать `null` и делать проверки. Например, сейчас на время загрузки митапа отображается "сломанная" страница с пустыми значениями.

Проверки нужны в двух местах: в вычисляемых свойствах, чтобы не было обращений к свойствам у `null`, и где-нибудь на верхнем уровне в шаблоне с `v-if`, чтобы не выводить страницу с данными митапа, пока нет данных митапа.

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +  },
В JS не нужен цикл, чтобы обратиться к полю объекта по ключу. Достаточно квадратных скобок: `agendaItemIcons[item.type]`

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +  },
Кроме того, методы обычно называют set, если они что-то устанавливают. Эти методы ничего не устанавливают, только вычисляют и возвращают значение.

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +    })
Дата и imageId - это не самостоятельные данные. Их нет причин хранить отдельно от свойства `rawMeetup`.

Храня их отдельно, вы разрываете связь между частью данных митапа (датой и картинкой) и всеми данными митапа в целом.

Например, так вам придётся всегда помнить об этом и не забывать обновлять эти свойства, если данные митапа обновятся.

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +    },
Вычисляемые свойства - это свойства. Описывая их мы передаём функцию в свойство с таким же именем, но это всё ещё свойство, и именовать его принято, как свойство, а не как метод (не с глагола).

2021-05-23 20:20 UTC, ShGKme commented on 01-basics/04-MeetupPageDraft/script.js
> +    },
Вычисляемое свойство - это свойство, в котором хранится некоторое значение, которое Vue будет вычислять вашей функцией.

Описывается оно функцией, которая на основе каких-то данных **вычисляет** новые данные.

Vue будет вызывать эту функцию для вычисления нового значения вычисляемого свойства при изменении данных, от которых оно зависит.

Таким образом, **вычисляемые свойства ни в коем случае не должны иметь побочных эффектов**.

Это вычисляемое свойство не вычисляет данные, а изменяет их.

Кроме того, вы используете метод map отображения данных не для отображения данных, а как обычный цикл.

2021-05-23 20:20 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
> +      if(this.link !== null){
При отсутствии ссылки могут передать не `null`, а какое-то другое `falsy` значение. Лучше оставить проверкой просто `if (!this.link)`

2021-05-24 20:02 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-24 20:25 UTC, ShGKme requested changes
Проблемы с 04-MeetupPageDraft остались, остальные задачи приняты

2021-05-24 20:25 UTC, ShGKme commented on 02-components/03-MeetupCover/MeetupCover.js
> +      }
Этот else ничего не делает, функция итак завершит работу вернув ничего.

2021-05-25 07:17 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-25 07:20 UTC, la-rivolta commented
> Проблемы с 04-MeetupPageDraft остались, остальные задачи приняты

@ShGKme, добрый день!
С первого раза не запушилось решение 04-MeetupPageDraft, сейчас исправления должны по пасть в ветку.

2021-05-25 08:23 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-05-25 08:24 UTC, merged